title: "MARGINALIA"
description: "Notes in the Margin"

# For project sites:
url: "https://pittsy.github.io"
baseurl: "/marginalia"

markdown: kramdown
theme: null

permalink: /:year/:month/:day/:title/

plugins: []
